[2015-03-12 01:06:57] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function exists() on a non-object' in /home/codio/workspace/menus/app/Http/Controllers/MenuController.php:43
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-12 01:07:15] local.ERROR: exception 'ErrorException' with message 'Non-static method Illuminate\Http\Request::url() should not be called statically, assuming $this from incompatible context' in /home/codio/workspace/menus/app/Http/Controllers/MenuController.php:48
Stack trace:
#0 /home/codio/workspace/menus/app/Http/Controllers/MenuController.php(48): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2048, 'Non-static meth...', '/home/codio/wor...', 48, Array)
#1 [internal function]: App\Http\Controllers\MenuController->getDatosMenu('2')
#2 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#3 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('getDatosMenu', Array)
#4 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\MenuController), Object(Illuminate\Routing\Route), 'getDatosMenu')
#5 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 /home/codio/workspace/menus/app/Http/Middleware/Authenticate.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getDatosMenu')
#13 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'getDatosMenu')
#14 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Route.php(131): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#15 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#22 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(210): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#25 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/codio/workspace/menus/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#43 /home/codio/workspace/menus/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#44 {main}  
[2015-03-12 01:08:42] local.ERROR: exception 'ErrorException' with message 'Non-static method Illuminate\Http\Request::url() should not be called statically, assuming $this from incompatible context' in /home/codio/workspace/menus/app/Http/Controllers/MenuController.php:47
Stack trace:
#0 /home/codio/workspace/menus/app/Http/Controllers/MenuController.php(47): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2048, 'Non-static meth...', '/home/codio/wor...', 47, Array)
#1 [internal function]: App\Http\Controllers\MenuController->getDatosMenu('2')
#2 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(246): call_user_func_array(Array, Array)
#3 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(162): Illuminate\Routing\Controller->callAction('getDatosMenu', Array)
#4 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(107): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\MenuController), Object(Illuminate\Routing\Route), 'getDatosMenu')
#5 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 /home/codio/workspace/menus/app/Http/Middleware/Authenticate.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getDatosMenu')
#13 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'getDatosMenu')
#14 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Route.php(131): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#15 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#22 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(210): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#25 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/codio/workspace/menus/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#43 /home/codio/workspace/menus/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#44 {main}  
[2015-03-12 01:11:59] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\App' not found' in /home/codio/workspace/menus/app/Http/Controllers/MenuController.php:47
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-12 01:42:33] local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)' in /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=loca...', 'root', 'secret', Array)
#1 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(58): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(47): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(177): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(65): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3134): Illuminate\Database\DatabaseManager->connection(NULL)
#7 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3100): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1895): Illuminate\Database\Eloquent\Model->getConnection()
#9 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1836): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#10 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1810): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#11 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(44): Illuminate\Database\Eloquent\Model->newQuery()
#12 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(148): Illuminate\Auth\EloquentUserProvider->retrieveById('1')
#13 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(109): Illuminate\Auth\Guard->user()
#14 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(119): Illuminate\Auth\Guard->check()
#15 /home/codio/workspace/menus/app/Http/Middleware/Authenticate.php(35): Illuminate\Auth\Guard->guest()
#16 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(108): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\MenuController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getDatosMenu')
#21 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Route.php(198): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'getDatosMenu')
#22 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Route.php(131): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#23 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#30 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#31 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(210): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#33 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/codio/workspace/menus/app/Http/Middleware/VerifyCsrfToken.php(17): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(125): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#50 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(84): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#51 /home/codio/workspace/menus/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#52 {main}  
[2015-03-12 12:53:39] local.ERROR: exception 'InvalidArgumentException' with message 'There are no commands defined in the "lang" namespace.' in /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php:501
Stack trace:
#0 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(535): Symfony\Component\Console\Application->findNamespace('lang')
#1 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(192): Symfony\Component\Console\Application->find('lang:generate')
#2 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}  
[2015-03-12 12:56:27] local.ERROR: exception 'InvalidArgumentException' with message 'There are no commands defined in the "autolang" namespace.' in /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php:501
Stack trace:
#0 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(535): Symfony\Component\Console\Application->findNamespace('autolang')
#1 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(192): Symfony\Component\Console\Application->find('autolang:genera...')
#2 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}  
[2015-03-12 13:26:40] local.ERROR: exception 'InvalidArgumentException' with message 'There are no commands defined in the "autolang" namespace.' in /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php:501
Stack trace:
#0 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(535): Symfony\Component\Console\Application->findNamespace('autolang')
#1 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(192): Symfony\Component\Console\Application->find('autolang:genera...')
#2 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}  
[2015-03-12 13:29:27] local.ERROR: exception 'RuntimeException' with message 'Not enough arguments.' in /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Input/Input.php:77
Stack trace:
#0 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(248): Symfony\Component\Console\Input\Input->validate()
#1 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoLangBlade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main}  
[2015-03-12 13:30:25] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Console\Commands\App' not found' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:40
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-12 13:31:30] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Foundation\Application::base_path()' in /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:207
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-12 13:37:37] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '}'' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:47
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-12 13:41:16] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '$es_directorio' (T_VARIABLE)' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:47
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-12 13:41:35] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected '{'' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:45
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-12 13:41:48] local.ERROR: exception 'ErrorException' with message 'readdir() expects parameter 1 to be resource, string given' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:45
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'readdir() expec...', '/home/codio/wor...', 45, Array)
#1 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(45): readdir('app.blade.php')
#2 [internal function]: App\Console\Commands\AutoLangBlade->fire()
#3 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#4 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#5 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoLangBlade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 {main}  
[2015-03-12 13:42:41] local.ERROR: exception 'ErrorException' with message 'scandir(app.blade.php): failed to open dir: No such file or directory' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:45
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'scandir(app.bla...', '/home/codio/wor...', 45, Array)
#1 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(45): scandir('app.blade.php')
#2 [internal function]: App\Console\Commands\AutoLangBlade->fire()
#3 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#4 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#5 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoLangBlade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 {main}  
[2015-03-12 13:53:36] local.ERROR: exception 'ErrorException' with message 'Undefined variable: directory' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:47
Stack trace:
#0 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(47): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined varia...', '/home/codio/wor...', 47, Array)
#1 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(41): App\Console\Commands\AutoLangBlade->readdir('/home/codio/wor...')
#2 [internal function]: App\Console\Commands\AutoLangBlade->fire()
#3 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#4 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#5 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoLangBlade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 {main}  
[2015-03-12 13:53:51] local.ERROR: exception 'ErrorException' with message 'scandir(auth): failed to open dir: No such file or directory' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:47
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'scandir(auth): ...', '/home/codio/wor...', 47, Array)
#1 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(47): scandir('auth')
#2 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(56): App\Console\Commands\AutoLangBlade->readdir('auth')
#3 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(41): App\Console\Commands\AutoLangBlade->readdir('/home/codio/wor...')
#4 [internal function]: App\Console\Commands\AutoLangBlade->fire()
#5 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#6 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#7 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoLangBlade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  
[2015-03-12 13:57:16] local.ERROR: exception 'ErrorException' with message 'scandir(auth): failed to open dir: No such file or directory' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:47
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'scandir(auth): ...', '/home/codio/wor...', 47, Array)
#1 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(47): scandir('auth')
#2 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(56): App\Console\Commands\AutoLangBlade->readdir('auth')
#3 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(41): App\Console\Commands\AutoLangBlade->readdir('/home/codio/wor...')
#4 [internal function]: App\Console\Commands\AutoLangBlade->fire()
#5 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#6 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#7 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoLangBlade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  
[2015-03-12 18:45:29] local.ERROR: exception 'ErrorException' with message 'scandir(auth): failed to open dir: No such file or directory' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:48
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'scandir(auth): ...', '/home/codio/wor...', 48, Array)
#1 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(48): scandir('auth')
#2 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(57): App\Console\Commands\AutoLangBlade->readdir('auth')
#3 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(41): App\Console\Commands\AutoLangBlade->readdir('/home/codio/wor...')
#4 [internal function]: App\Console\Commands\AutoLangBlade->fire()
#5 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#6 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#7 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoLangBlade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  
[2015-03-12 18:46:21] local.ERROR: exception 'ErrorException' with message 'scandir(auth): failed to open dir: No such file or directory' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:48
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'scandir(auth): ...', '/home/codio/wor...', 48, Array)
#1 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(48): scandir('auth')
#2 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(58): App\Console\Commands\AutoLangBlade->readdir('auth')
#3 /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php(41): App\Console\Commands\AutoLangBlade->readdir('/home/codio/wor...')
#4 [internal function]: App\Console\Commands\AutoLangBlade->fire()
#5 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
#6 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#7 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AutoLangBlade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/codio/workspace/menus/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(90): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/codio/workspace/menus/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  
[2015-03-12 19:53:38] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Console\Commands\DOMDocument' not found' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:57
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-12 19:57:24] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Console\Commands\DOMDocument' not found' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:57
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-12 20:04:47] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Console\Commands\DOMDocument' not found' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:57
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
[2015-03-12 20:07:04] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Console\Commands\DOMDocument' not found' in /home/codio/workspace/menus/app/Console/Commands/AutoLangBlade.php:57
Stack trace:
#0 /home/codio/workspace/menus/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}  
